version: "3.7"
services:
  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ktracker
    volumes:
      - ./postgres-initdb.d:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
